#!/bin/sh

# Dieses Skript sollte eigentlich ein Symlink auf ip-up sein.
# Da man das aber nicht einchecken kann, ist es nun eine Kopie.

# Anmerkung: sh der busyshell kann keine (normales) if!

BASENAME=${0##*/}
INTERFACE=$1
DEVICE=$2
SPEED=$3
LOCALIP=$4
REMOTEIP=$5

if [ -z "$REMOTEIP" ]; then
    echo "Usage: $0 <INTERFACE> <DEVICE> <SPEED> <LOCALIP> <REMOTEIP>"
    exit 1
fi

TERM=raw
export TERM

. /etc/rc.config

case "$INTERFACE" in
ippp*)

    # find the device
#    found=0
#    for I in $NETCONFIG $NETCONFIG_PCMCIA; do
#	eval NETDEV=\$NETDEV$I
#	if [ $NETDEV = $INTERFACE ]; then
#	    found=1
#	    break;
#	fi
#    done
#    if [ $found -eq 0 ]; then
#	echo "Device '$INTERFACE' not configured in '/etc/rc.config'"
#	exit 1
#    fi

#    eval IFCONFIG=\$IFCONFIG$I

    case "$BASENAME" in
    ip-up)
	echo "d-box online" >/dev/dbox/lcd0
	# Get the nameservers (works with ipppd option ms-get-dns):

#	if [ -n "$MS_DNS1" -a "$START_NAMED" != "yes" ]; then
#		rm -f /etc/ppp/resolv.prev
#		if [ -f /etc/resolv.conf ]; then
#			cp -p /etc/resolv.conf /etc/ppp/resolv.prev
#			grep domain /etc/ppp/resolv.prev > /etc/resolv.conf
#			grep search /etc/ppp/resolv.prev >> /etc/resolv.conf
#			echo "nameserver $MS_DNS1" >> /etc/resolv.conf
#			echo "nameserver $MS_DNS2" >> /etc/resolv.conf
#			echo "Modified /etc/resolv.conf for DNS at $INTERFACE"
#		else
#			echo "nameserver $MS_DNS1" >> /etc/resolv.conf
#			echo "nameserver $MS_DNS2" >> /etc/resolv.conf
#			chmod 644 /etc/resolv.conf
#			echo "Installed /etc/resolv.conf for DNS at $INTERFACE"
#		fi
#	fi

	# call ip-up.local if it exists and is executable:
	test -x /etc/ppp/ip-up.local && /etc/ppp/ip-up.local "$@"
	;;
    ip-down)
	echo "d-box offline" >/dev/dbox/lcd0

	# Restore the nameservers (got with ipppd option ms-get-dns):

#	if [ -n "$MS_DNS1" -a "$START_NAMED" != "yes" ]; then
#		if [ -f /etc/ppp/resolv.prev ]; then
#			cp -fp /etc/ppp/resolv.prev /etc/resolv.conf
#			echo "Restored original /etc/resolv.conf"
		#else
		#	rm -f /etc/resolv.conf
		#	echo "Deinstalled /etc/resolv.conf"
#		fi
#	fi

	# restart interface
#	/sbin/ifconfig $INTERFACE $IFCONFIG
	# set routes from /etc/route.conf 
#	/etc/init.d/route start $INTERFACE

	# call ip-down.local if it exists and is executable:
	test -x /etc/ppp/ip-down.local && /etc/ppp/ip-down.local "$@"
	;;
    *)
	;;
    esac
    ;;

ppp*)
    # Analog-PPP, add commands as you need...
    case "$BASENAME" in
    ip-up)
	#
	# This code allows automatic configuration of your resolv.conf
	# for peer supplied DNS addresses when using the `usepeerdns'
	# option. Original resolv.conf is restored when ip-down is called
	# by pppd when the link goes down.
	#
#	if [ -n "$USEPEERDNS" -a -f /etc/ppp/resolv.conf -a "$START_NAMED" != "yes" ]; then
#		rm -f /etc/ppp/resolv.prev
#		if [ -f /etc/resolv.conf ]; then
#			cp -p /etc/resolv.conf /etc/ppp/resolv.prev
#			grep domain /etc/ppp/resolv.prev > /etc/resolv.conf
#			grep search /etc/ppp/resolv.prev >> /etc/resolv.conf
#			cat /etc/ppp/resolv.conf >> /etc/resolv.conf
#			echo "Modified /etc/resolv.conf for DNS at $INTERFACE"
#		else
#			cp /etc/ppp/resolv.conf /etc
#			chmod 644 /etc/resolv.conf
#			echo "Installed /etc/resolv.conf for DNS at $INTERFACE"
#		fi
#	fi

	# call ip-up.local if it exists and is executable:
	test -x /etc/ppp/ip-up.local && /etc/ppp/ip-up.local "$@"
	;;
    ip-down)
	#
	# This code restores the original resolv.conf saved when ip-up
	# was called by the pppd which uses the `usepeerdns' option and
	# resolv.conf was modified for the supplied dns server adresses.
	#
#	if [ -n "$USEPEERDNS" -a -f /etc/ppp/resolv.conf -a "$START_NAMED" != "yes" ]; then
#		if [ -f /etc/ppp/resolv.prev ]; then
#			cp -fp /etc/ppp/resolv.prev /etc/resolv.conf
#			echo "Restored original /etc/resolv.conf"
#		else
#			rm -f /etc/resolv.conf
#			echo "Deinstalled /etc/resolv.conf"
#		fi
#	fi
	# call ip-down.local if it exists and is executable:
	test -x /etc/ppp/ip-down.local && /etc/ppp/ip-down.local "$@"
	;;
    *)
	;;
    esac
    ;;
*)
    # dont know...
    ;;
esac # | logger -p security.notice -t $BASENAME
