#!/bin/sh

killall -9 startmenu

echo "Lade sectionsd"
/bin/sectionsd

echo "Lade zapit"
/bin/zapit

echo "Lade lcd"
$INSMOD /lib/modules/`uname -r`/misc/lcd.o

echo "Lade lcdd"
/bin/lcdd

echo "Lade controld"
/bin/controld

echo "Starting nhttpd"
/bin/nhttpd &

echo "Starte Neutrino"
/bin/neutrino
