#!/bin/sh

. /etc/profile

if test -x /bin/lcdmenu ; then
  lcdmenu
  RC="$?"
  test "$RC" -eq 0 && /bin/enigma
  test "$RC" -eq 1 && /etc/init.d/start_neutrino
  test "$RC" -eq 2 && /etc/init.d/start_lcars
elif test -x /bin/neutrino ; then
  /etc/init.d/start_neutrino
elif test -x /bin/enigma ; then
  /bin/enigma
elif test -x /bin/lcars ; then
  /etc/init.d/start_lcars
fi

/sbin/halt