#!/bin/sh

trap '' HUP INT

if test ! -f /etc/ssh/ssh_host_key ; then
	echo "Creating SSH1 key"
	ssh-keygen -f /etc/ssh/ssh_host_key -N '' > /dev/null
fi
if test ! -f /etc/ssh/ssh_host_rsa_key ; then
	echo "Creating SSH2 RSA key"
	ssh-keygen -f /etc/ssh/ssh_host_rsa_key -N '' -t rsa > /dev/null
fi
if test ! -f /etc/ssh/ssh_host_dsa_key ; then
	echo "Creating SSH2 DSA key"
	ssh-keygen -f /etc/ssh/ssh_host_dsa_key -N '' -t dsa > /dev/null
fi

sshd

