#!/bin/sh
insmod avs type=2 debug=0
insmod saa7126 board=1 debug=0
insmod event
insmod fp debug=0 useimap=0
insmod avia pal=1 debug=0 firmware=/var/ucodes
insmod enx_core debug=0
insmod demux
insmod cam debug=0 firmware=/var/ucodes/cam-alpha.bin
insmod dmxdev
insmod dvbdev
#insmod dvb_frontend
insmod dvb
#insmod dvb_net
insmod tda8044h debug=0
insmod enx_dmx debug=0 ucode=/var/ucodes/ucode.bin
insmod enx_vbi
insmod enx_fb debug=0
insmod enx_capture
#insmod osd
