#!/bin/sh
insmod avs type=0 debug=0
insmod saa7126 board=1 debug=0
insmod event
insmod fp debug=0 useimap=0
insmod avia pal=1 debug=0 firmware=/var/ucodes
insmod gtx_core debug=0
insmod demux
insmod cam debug=0 firmware=/var/ucodes/cam-alpha.bin
insmod dmxdev
insmod dvbdev
#insmod dvb_frontend
insmod dvb
#insmod dvb_net
insmod ves1893 debug=0
insmod gtx_dmx debug=0 ucode=/var/ucodes/ucode.bin
insmod gtx_vbi
insmod gtx_fb debug=0
insmod gtx_capture
insmod gtx_pig
#insmod osd
