#!/bin/sh

# Tuxbox init script for /bin/hwrtc

case $1 in
	start)
		if [ -e /var/etc/.rtc ]; then
			$IM ds1307
			sleep 1
			hwrtc hwtosys
		fi
		;;
	stop)
		if [ ! -e /proc/clock ]; then
			$IM ds1307
			sleep 1
		fi
		hwrtc systohw
		;;
esac

exit 0
