#!/bin/sh

# Tuxbox init script for /bin/hwrtc

case $1 in
	start)
		$IM ds1307
		sleep 1
		hwrtc hwtosys
		;;
	stop)
		if [ ! -e /proc/clock ]; then
			$IM ds1307
			sleep 1
		fi
		hwrtc systohw
		;;
esac

exit 0
