#!/bin/sh

# Tuxbox init script for /bin/tuxmaild

PROG=tuxmaild

case $1 in
	start)
		[ -e /var/etc/.$PROG ] && $PROG
		;;
	stop)
		[ -e /var/run/$PROG.pid ] && kill $( cat /var/run/$PROG.pid )
		;;
esac

exit 0
