#!/bin/sh

# $Id: halt,v 1.2 2006/03/29 12:38:04 saruman Exp $

[ -e /tmp/tuxmaild.pid ] && kill $( cat /tmp/tuxmaild.pid )
[ -e /tmp/tuxcald.pid ] && kill $( cat /tmp/tuxcald.pid )

/bin/switch -fnc 0
