#!/bin/sh

# $Id: halt,v 1.5 2009/04/28 08:08:36 seife Exp $

mount | grep /hdd >/dev/null && umount /hdd

[ -e /var/run/automount.pid ] && kill -TERM $( cat /var/run/automount.pid )
[ -e /tmp/tuxmaild.pid ] && kill $( cat /tmp/tuxmaild.pid )
[ -e /tmp/tuxcald.pid ] && kill $( cat /tmp/tuxcald.pid )

switch -fnc 0 -fblk 0

mount | grep /var >/dev/null && umount /var
umount -l /var
