#!/bin/sh

# $Id: halt,v 1.3 2006/09/24 10:08:16 barf Exp $

[ -e /var/run/automount.pid ] && kill -TERM $( cat /var/run/automount.pid )
[ -e /tmp/tuxmaild.pid ] && kill $( cat /tmp/tuxmaild.pid )
[ -e /tmp/tuxcald.pid ] && kill $( cat /tmp/tuxcald.pid )

switch -fnc 0 -fblk 0
