#!/bin/sh

PATH=/sbin:/bin

# extract kernel minor without using cut
OLD_IFS=IFS
IFS='.'
get_second() { echo $2; }
KMINOR=`get_second $(uname -r)`
IFS=$OLD_IFS

hostname -F /etc/hostname
mount -a

if [ $KMINOR -ge 6 ]; then
	if [ ! -d /dev/pts ]; then
		# create necessary nodes,
		# static for now
		mkdir /dev/pts
		mknod /dev/tty c 5 0
		mknod /dev/tty0 c 4 0
		mknod /dev/tty1 c 4 1
		mknod /dev/tty2 c 4 2
		mknod /dev/tty3 c 4 3
		mknod /dev/ptmx c 5 2

		mknod /dev/urandom c 1 9
		mknod /dev/random c 1 8

		# this is fragile because
		# it's module load order
		# dependent
		mkdir /dev/dbox
		mknod /dev/dbox/avs0 c 10 60
		mknod /dev/dbox/event0 c 10 63
		mknod /dev/dbox/fp0 c 10 62
		mknod /dev/dbox/lcd0 c 10 59
		mknod /dev/dbox/saa0 c 10 58
		mknod /dev/dbox/dvb2eth c 10 57

		mknod /dev/watchdog c 10 130
		mknod /dev/lirc c 10 61

		mkdir /dev/dvb
		mkdir /dev/dvb/adapter0
		mknod /dev/dvb/adapter0/audio0 c 212 1
		mknod /dev/dvb/adapter0/ca0 c 212 6
		mknod /dev/dvb/adapter0/ca1 c 212 22
		mknod /dev/dvb/adapter0/demux0 c 212 4
		mknod /dev/dvb/adapter0/dvr0 c 212 5
		mknod /dev/dvb/adapter0/frontend0 c 212 3
		mknod /dev/dvb/adapter0/net0 c 212 7
		mknod /dev/dvb/adapter0/video0 c 212 0
		
		mknod /dev/fb0 c 29 0

		mkdir /dev/fb
		ln -sf /dev/fb0 /dev/fb/0
		
		mkdir /dev/vc
		ln -sf /dev/tty0 /dev/vc/0
		
		mkdir /dev/v4l
		mknod /dev/v4l/video0 c 81 0
		
		mkdir /dev/sound
		mknod /dev/sound/dsp c 14 3
		mknod /dev/sound/mixer c 14 0
		mknod /dev/sound/mixer1 c 14 16
		
		mkdir /dev/input
		mknod /dev/input/event0 c 13 64
		mknod /dev/input/mice c 13 63
	fi
	mount /dev/pts
fi

ifup -a
test -x /sbin/inetd && inetd

if test -x /sbin/sshd ; then
	/etc/init.d/start_sshd &
fi

if [ -r /var/etc/dropbear/dropbear_dss_host_key -a -r /var/etc/dropbear/dropbear_rsa_host_key ]; then
	/sbin/dropbear
fi

if test -x /sys ; then
	mount /sys
fi

touch /etc/modules.conf
depmod -ae
modprobe tuxbox

. /etc/profile

VENDOR=`/bin/tuxinfo -V`
VENDOR_ID=`/bin/tuxinfo -v`
MODEL=`/bin/tuxinfo -M`
MODEL_ID=`/bin/tuxinfo -m`
SUBMODEL=`/bin/tuxinfo -S`
SUBMODEL_ID=`/bin/tuxinfo -s`

echo "Detected STB:"
echo "  Vendor: $VENDOR"
echo "  Model: $MODEL $SUBMODEL"

if [ $KMINOR -ge 6 ]; then
	# kernel 2.6
	modprobe dbox2_i2c
	modprobe dbox2_napi

	modprobe dbox2_fp_input

	modprobe avia_gt_fb
	modprobe avia_gt_lirc
	modprobe avia_gt_oss
	modprobe avia_gt_v4l2

	modprobe avs
	modprobe lcd
	modprobe saa7126
	modprobe dvb2eth
else
	# kernel 2.4
	modprobe dvb-core

	# I2C core

	modprobe dbox2_i2c
	modprobe dvb_i2c_bridge
	
	# Frontprozessor
	modprobe dbox2_fp
	modprobe dbox2_fp_input

	# Frontends
	# Nokia
	if [ $VENDOR_ID -eq 1 ]; then
		modprobe ves1820
		modprobe ves1x93 board_type=1
	# Philips
	elif [ $VENDOR_ID -eq 2 ]; then
		modprobe tda8044h
	# Sagem
	elif [ $VENDOR_ID -eq 3 ]; then
		modprobe at76c651
		modprobe ves1x93 board_type=2
	fi

	# Misc IO
	modprobe avs
	modprobe saa7126
	# Philips
	if [ $VENDOR_ID -eq 2 ]; then
		modprobe cam mio=0xC040000
	else
		modprobe cam mio=0xC000000
	fi
	modprobe lcd

	# A/V
	if [ -f /var/etc/.no_watchdog ]; then
		modprobe avia_av no_watchdog=1
	else
		modprobe avia_av
	fi

	GTOPTS=""
	if [ -e /var/etc/.hw_sections ]; then
		GTOPTS="hw_sections=0 "
	fi
	if [ -e /var/etc/.no_enxwatchdog ]; then
		GTOPTS="${GTOPTS}no_watchdog=1 "
	fi

	modprobe avia_gt 	ucode=/var/tuxbox/ucodes/ucode.bin ${GTOPTS}
	  
	modprobe avia_gt_fb
	modprobe avia_gt_lirc
	modprobe avia_gt_oss
	modprobe avia_gt_v4l2

	modprobe avia_napi
	modprobe cam_napi
	modprobe avia_av_napi
	if [ -e /var/etc/.spts_mode ]; then
		modprobe avia_gt_napi mode=1
		modprobe dvb2eth
	else
		modprobe avia_gt_napi
	fi

	modprobe aviaEXT
	modprobe dbox2_fp_napi

fi


echo "$VENDOR $MODEL - Kernel %r (%t)." > /etc/issue.net

if [ $KMINOR -lt 6 ]; then
	# compatibility links
	ln -sf demux0 /dev/dvb/adapter0/demux1
	ln -sf dvr0 /dev/dvb/adapter0/dvr1
	ln -sf fb/0 /dev/fb0
fi

test -x /bin/loadkeys && loadkeys /share/keymaps/i386/qwertz/de-latin1.kmap.gz

if [ ! -d /var/etc ] ; then
    mkdir /var/etc
fi

if [ -e /etc/init.d/rcS.local ]; then
	. /etc/init.d/rcS.local
fi
