#!/bin/sh

echo "Lade sectionsd"
/bin/sectionsd

echo "Lade zapit"
/bin/zapit

echo "Lade lcdd"
/bin/lcdd

echo "Lade controld"
/bin/controld

echo "Starting nhttpd"
/bin/nhttpd &

echo "Starte Neutrino"
/bin/neutrino
