#!/bin/sh

. /etc/profile

if [ -x /bin/lcdmenu ] ; then
    exec /bin/lcdmenu
elif [ -x /bin/neutrino ] ; then
    exec /etc/init.d/start_neutrino
elif [ -x /bin/enigma ] ; then
    exec /etc/init.d/start_enigma
elif [ -x /bin/lcars ] ; then
    exec /etc/init.d/start_lcars
elif [ -x /bin/radiobox ] ; then
    exec /etc/init.d/start_radiobox
else
    echo ""
    echo "No GUI found."
fi
