#!/bin/sh

# $Id: start_esound,v 1.2 2009/03/24 20:37:59 rhabarber1848 Exp $

ESD=/bin/esd

if [ -x /var/bin/esd ] ; then
	ESD=/var/bin/esd
fi

$ESD -tcp -public -nobeeps -d /dev/sound/dsp -r 44100 &
