#!/bin/sh

# $Id: start_lcars,v 1.7 2006/03/29 13:52:56 saruman Exp $

# lcars doesn't need a camd, so we should shut it down here. That
# isn't nice, I should think about a better solution asap.
if pidof camd2 > /dev/null; then killall camd2

lcars > /dev/null
