#!/bin/sh

# $Id: start_neutrino,v 1.25 2005/10/21 09:39:31 barf Exp $

date -s 010101001970
sectionsd
timerd
camd2
zapit
controld
nhttpd
neutrino -f -u

[ -e /tmp/tuxmaild.pid ] && kill $( cat /tmp/tuxmaild.pid )
pzapit -kill

i=9
while expr $i != 0 > /dev/null
do
if pidof controld > /dev/null; then echo "Waiting for controld (max. $i seconds)"
elif pidof timerd > /dev/null; then echo "Waiting for timerd (max. $i seconds)"
elif pidof zapit > /dev/null; then echo "Waiting for zapit (max. $i seconds)"
elif pidof tuxmaild > /dev/null; then echo "Waiting for tuxmaild (max. $i seconds)"
else break;
fi
i=`expr $i - 1`
sleep 1
done
halt
