#!/bin/sh
#
# /etc/init.d/sysinit
#
# mounts virtual filesystems etc and /var, so that the system can boot

mount -t proc	proc	/proc
mount -t tmpfs	tmp	/tmp
echo "[BOOT] running $0"

mount -t tmpfs dev /dev
mount -t sysfs sys /sys
echo "/sbin/hotplug" > /proc/sys/kernel/hotplug
# create necessary nodes,
# static for now, i am just too lazy for udev :-)
cd /dev
mkdir -p pts dbox dvb/adapter0 loop i2c input sound v4l fb vc mtdblock mtd tts
# kernel 2.4 gets this via devfs?
mount -t devpts devpts /dev/pts

if type -p makedevices; then
	makedevices
else
	# in theory, now it is too late to create /dev/console...
	mknod console c 5 1
	mknod null c 1 3
	mknod tty c 5 0
	mknod tty0 c 4 0
	mknod tty1 c 4 1
	mknod tty2 c 4 2
	mknod tty3 c 4 3
	mknod ptmx c 5 2

	mknod urandom c 1 9
	mknod random c 1 8
	mknod mem c 1 1
	mknod kmem c 1 2

	mknod watchdog c 10 130

	mknod dvb/adapter0/audio0 c 212 1
	mknod dvb/adapter0/ca0 c 212 6
	mknod dvb/adapter0/ca1 c 212 22
	mknod dvb/adapter0/demux0 c 212 4
	mknod dvb/adapter0/dvr0 c 212 5
	mknod dvb/adapter0/frontend0 c 212 3
	mknod dvb/adapter0/net0 c 212 7
	mknod dvb/adapter0/video0 c 212 0

	mknod fb0 c 29 0

	mknod v4l/video0 c 81 0

	mknod sound/dsp c 14 3
	mknod sound/mixer c 14 0
	mknod sound/mixer1 c 14 16

	mknod input/event0 c 13 64
	mknod input/mouse0 c 13 32
	mknod input/mice c 13 63

	mknod i2c/0 c 89 0

	# 6 loop devices are enough.
	for i in 0 1 2 3 4 5; do
		mknod loop/$i b 7 $i
		mknod mtdblock/$i b 31 $i
	done
	mknod mtd/0 c 90 0
	mknod mtd/1 c 90 2
	mknod mtd/2 c 90 4
	mknod mtd/3 c 90 6
	mknod mtd/4 c 90 8
	mknod mtd/5 c 90 10
	mknod mtd/0ro c 90 1
	mknod mtd/1ro c 90 3
	mknod mtd/2ro c 90 5
	mknod mtd/3ro c 90 7
	mknod mtd/4ro c 90 9
	mknod mtd/5ro c 90 11
	mknod tts/0 c 4 64
	mknod tts/1 c 4 65
fi
# devices with dynamic minor numbers are created by /sbin/hotplug

ln -sf /dev/fb0 fb/0
ln -sf /dev/tty0 vc/0
ln -sf /dev/tty1 vc/1
ln -sf /dev/tty2 vc/2
ln -sf /dev/tty3 vc/3
ln -sf /dev/tty4 vc/4
ln -sf /dev/tty5 vc/5
ln -sf /dev/tty6 vc/6
cd /

date -s 010101001970

ROOTFS=$(grep /dev/root /proc/mounts | cut -d " " -f 3)

if [ "$ROOTFS" != "nfs" ]; then

	# find the device of the /var/ partition
	# after that $VAR_MTD contains "/dev/mtdblock/3"
	eval $(sed -n 's#^mtd\([0-9]\): .* .* "var .*$#export VAR_MTD=/dev/mtdblock/\1#p;' /proc/mtd)

	# this needs to come after "makedevices" for kernel 2.6...
	if [ -n "$VAR_MTD" ]; then
		mount -t jffs2 $VAR_MTD /var
	else
		echo "[BOOT] no /var MTD partition found (jffs2-image?)"
	fi

fi
